development:
  adapter: postgresql
  database: fabricipsum_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: fabricipsum_test
  host: localhost
  pool: 5
  timeout: 5000t

production:
  adapter: postgresql
  database: fabricmuch_production
  host: localhost
  pool: 5
  timeout: 5000
